// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFileToDownloads(arg1, arg2) {
  return window['go']['main']['App']['CopyFileToDownloads'](arg1, arg2);
}

export function ExecutePalm(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecutePalm'](arg1, arg2, arg3);
}

export function ExecutePythonScript(arg1, arg2) {
  return window['go']['main']['App']['ExecutePythonScript'](arg1, arg2);
}

export function GetFilenames(arg1) {
  return window['go']['main']['App']['GetFilenames'](arg1);
}

export function GetLiabilityConfigs(arg1) {
  return window['go']['main']['App']['GetLiabilityConfigs'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function ReadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFiles'](arg1, arg2, arg3);
}

export function ReadScenarioConfig(arg1) {
  return window['go']['main']['App']['ReadScenarioConfig'](arg1);
}

export function ReadUIConfig() {
  return window['go']['main']['App']['ReadUIConfig']();
}

export function WriteJsonFile(arg1, arg2) {
  return window['go']['main']['App']['WriteJsonFile'](arg1, arg2);
}
