// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLiabilityConfigs(arg1:string):Promise<Array<main.LiabilityConfigData>>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:main.FileDialogOptions):Promise<string>;

export function ReadUIConfig():Promise<main.Config>;
